version: "3.5"
services:
  frontend:
    image: hello-frontend:latest
    container_name: 'hello_frontend'
    ports:
    - '9000:80'
    - '9001:9001'
  backend:
    image: hello-backend:latest
    container_name: 'hello_backend'
    ports:
    - '9100:9000'
    - '9101:9001'
  prometheus:
    image: hello-prometheus:latest
    container_name: 'hello_prometheus'
    ports:
    - '9090:9090'
  grafana:
    image: hello-grafana:latest
    container_name: 'hello_grafana'
    ports:
    - '3000:3000'
    depends_on:
    - prometheus
networks:
  default:
    name: hello-network
    driver: bridge
