version: "3.8"
services:
  bff:
    image: hello-bff:latest
    container_name: "hello_bff"
    ports:
      - "9001:9001"
  frontend:
    image: hello-frontend:latest
    container_name: "hello_frontend"
    ports:
      - "9000:9000"
    depends_on:
      - bff
  prometheus:
    image: hello-prometheus:latest
    container_name: "hello_prometheus"
    ports:
      - "9090:9090"
  grafana:
    image: hello-grafana:latest
    container_name: "hello_grafana"
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
networks:
  default:
    name: hello-network
    driver: bridge
