version: "3.8"
services:
  backend:
    image: hello-backend:latest
    container_name: "hello_backend"
    ports:
      - "9001:9001"
  frontend:
    image: hello-frontend:latest
    container_name: "hello_frontend"
    ports:
      - "9000:9000"
    depends_on:
      - backend
  prometheus:
    image: hello-prometheus:latest
    container_name: "hello_prometheus"
    ports:
      - "9090:9090"
networks:
  default:
    name: hello-network
    driver: bridge
