---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-deployment
  namespace: hello
spec:
  selector:
    matchLabels:
      app: hello_bff
  replicas: 2
  template:
    metadata:
      labels:
        app: hello_bff
    spec:
      containers:
        - name: hello-bff
          image: dmanojbaba/hello-bff:latest
          env:
            - name: BACKEND_URL
              value: http://backend-service.hello.svc
          ports:
            - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: bff-service
  namespace: hello
spec:
  type: ClusterIP
  selector:
    app: hello_bff
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001
