---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  namespace: hello
data:
  prometheus.yml: |
    global:
      scrape_interval: 1m
      scrape_timeout: 10s
      evaluation_interval: 1m
    scrape_configs:
      - job_name: "hello-services"
        scrape_interval: 30s
        metrics_path: "/metrics"
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - hello
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello_prometheus
  template:
    metadata:
      labels:
        app: hello_prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.45.3
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
      serviceAccountName: prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-configmap
            defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: hello
spec:
  type: ClusterIP
  selector:
    app: hello_prometheus
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
      name: http
