# -- BUILD --
FROM gradle:8.6-jdk21-alpine as build

WORKDIR /usr/src/app

COPY . .

RUN gradle init
RUN gradle build

# -- RELEASE --
FROM openjdk:23-jdk

WORKDIR /app

COPY --from=build /usr/src/app/build/libs/hello-backend-*.jar hello-backend.jar
COPY entrypoint.sh entrypoint.sh

ENTRYPOINT [ "./entrypoint.sh", "hello-backend.jar" ]
